### PR TITLE
Added autoprefixing protocol when typing URL

### PR DESCRIPTION
**Pull request by Piterden**
Some JS magic

### CODE REVIEW

**Comment by RyanThompson** [comment]
This needs to be jquery as well and include the data-initialized logic from other input.js files around. 

Also needs to consider pasting in URLs on paste - take protocol from the paste input

**Comment by Piterden** [comment]
Got it

**Comment by Piterden** [comment]
If there is else - you could just mark `-> jQuery` ))

**Comment by Piterden** [comment]
What exactly data-initialized logic do you want there?

**Comment by RyanThompson** [comment]
Like dis: https://github.com/anomalylabs/url-field_type/commit/2b812a7d9756cf6c19051ae36ceb8b864e2fdf49#diff-673bce9d8e1f9fca31994ecc9cc97294R4

**Comment by RyanThompson** [comment]
So when it's reloaded over Ajax within repeater / grid it doesn't double up.

**Pull request merged**
