### PR TITLE
Fix undefined method error caused by reference to Laravel 5.4 UrlGenerator method.

### PR DESCRIPTION
**Pull request by fryiee**
- Add polyfill formatScheme method to replace undefined Laravel 5.4 UrlGenerator method
- Change normalize() method to use new formatScheme method

### CODE REVIEW

**Comment by fryiee** [comment]
In hindsight, the polyfill method should probably go directly on the Streams UrlGenerator, not on the URL Field Type (in case this ends up being used in other methods across core). This will require an additional PR for streams-platform if necessary.

**Comment by fryiee** [comment]
I'm going to move this into UrlGenerator as it makes more sense semantically.

**Comment by fryiee** [comment]
I'm closing this PR and moving the changes directly into streams-platform: https://github.com/anomalylabs/streams-platform/pull/440

**Comment by RyanThompson** [comment]
Nah this is correct - needs split for streams platform. Fixing.

**Comment by RyanThompson** [comment]
This should be resolved

**Comment by stockhausen** [comment]
same problem when you switch in another language 

An exception has been thrown during the rendering of a template ("Method Anomaly\UrlFieldType\UrlFieldTypePresenter::__toString() must return a string value")

**Comment by RyanThompson** [comment]
Forced to string

**Pull request closed without merging**
